package com.trafegus.poc.model;

public enum PermissaoEnum {
    ADMIN, SEND_LOGS,
    CONFIG_READ, CONFIG_WRITE, CONFIG_UPDATE, CONFIG_DELETE,
    VIAGEM_READ, VIAGEM_WRITE, VIAGEM_UPDATE, VIAGEM_DELETE
}
