version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-trafegus
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo_network

  redis:
    image: redis:latest
    container_name: redisdb-trafegus
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis_network

  localstack:
    image: localstack/localstack
    container_name: localstack-trafegus
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
    volumes:
      - localstack-data:/tmp/localstack
    networks:
      - localstack_network

  app:
      build: .
      container_name: flask-app-trafegus
      ports:
        - "5005:5005"
      volumes:
         - ./src:/src
      depends_on:
        - mongo
        - redis
        - localstack
      networks:
        - localstack_network
        - redis_network
        - mongo_network

networks:
  redis_network:
    driver: bridge
  localstack_network:
    driver: bridge
  mongo_network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  localstack-data: