version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-trafegus
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redisdb-trafegus
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  localstack:
    image: localstack/localstack
    container_name: localstack-trafegus
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
    volumes:
      - localstack-data:/tmp/localstack

volumes:
  mongo-data:
  redis-data:
  localstack-data:
